### PR TITLE
fix #88

### LINKED ISSUE #88: Deleting an expectation in passthrough mode does not restore original function
```
1> meck:new(string, [passthrough, no_link, unstick]).
ok
2> meck:expect(string, len, 1, 12).
ok    
3> string:len("apa").
12
4> meck:delete(string, len, 1).
ok
5> string:len("apa").
** exception error: undefined function string:len/1
```

### PR DESCRIPTION
**Pull request by yutopp**
fix #88.
Added `delete/4` which has a flag to delete a function even if the module has a `passthrough` option. Now, default `delete/3` doesn't delete a function(replace to a passthrough entry implicitly) if the module has a `passthrough` option.

Thanks.

### CODE REVIEW

File: test/meck_tests.erl [hunk 1]
```diff
@@ -1488,6 +1488,35 @@ wait_purge_expired_tracker_test() ->
...
+                           fun ?MODULE:delete_passthrough_/1,
+                           fun ?MODULE:delete_passthrough_force_/1
+                          ]]}.
+
+setup_passthrough() ->
+    % Uncomment to run tests with dbg:
+    % dbg:tracer(),
+    % dbg:p(all, call),
+    % dbg:tpl(meck, []),
+    ok = meck:new(mymod_pass, [passthrough, non_strict]),
```
Comment (eproxus) [inline test/meck_tests.erl]: Would it be possible to use the `meck_test_module` here? Then we wouldn't have to add a new module to tests.

File: src/meck.erl [hunk 2]
```diff
@@ -288,19 +289,32 @@ loop(Mod, Func, Ari, Loop) when is_list(Mod) ->
...
-    lists:foreach(fun(M) -> delete(M, Func, Ari) end, Mod),
+    meck_proc:delete_expect(Mod, Func, Ari, Force);
+delete(Mod, Func, Ari, Force) when is_list(Mod) ->
+    lists:foreach(fun(M) -> delete(M, Func, Ari, Force) end, Mod),
     ok.
 
+%% @doc Deletes an expectation.
+%%
+%% Deletes the expectation for the function `Func' with the matching
+%% arity `Arity'. See {@link delete/4}.
```
Comment (eproxus) [inline src/meck.erl]: Can you add an explanation here that if the mock has passthrough enabled, it will be restored instead of deleted?

**Comment by eproxus** [comment]
Thanks for a very clear patch!

Can you do two things? Squash the commits into one and capitalize the commit message, and make sure the code has a max line width of 80?

**Comment by yutopp** [comment]
Thank you very mush for your quick response.

- [x] use `meck_test_module` instead of `mymod_pass`
- [x] add detailed documents
- [x] squash commits and capitalize the commit message
- [x] check the max line width

Thanks!

**Comment by eproxus** [comment]
Brilliant! Thanks so much!
