### PR TITLE
Fix some static analysis issues (xref + dialyzer)

### LINKED ISSUE #218: References to hamcrest yield dialyzer warnings
While doing `rebar3 as test dialyzer`, which will eventually include `meck` in its analysis, I get warnings for references to `hamcrest:` types (which are outside the scope of the analysis, since `hamcrest` is not imported).

Would you be OK if I (PR) removed references to those types replacing them with an appropriate name and content?

e.g.

```erlang
HamcrestMatcher :: hamcrest:matchspec().
```

would become

```erlang
HamcrestMatcher :: record(). % hamcrest:matchspec().
```

(since there really is no strong link between the two anymore)

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
[Fix #218]

It started with me wanting to get rid of `hamcrest` -related warnings, since it's "used" but not imported by `meck`. And I write "used" because there is code to make sure it's there, before it's being used (and even `catch` clauses, at times), but the `dialyzer` doesn't care about that and complains in any way.

I guess I'll have to import `hamcrest` in the `deps` profile (on my lib.) just to force a correct analysis.

Though I did not get rid of all the warnings I wanted to get rid of, I still ended up doing a bit of clean-up, which you might want to merge.

### CODE REVIEW

File: src/meck_cover.erl [hunk 1]
```diff
@@ -22,6 +22,11 @@
 -export([rename_module/2]).
 -export([dump_coverdata/1]).
 
+-ignore_xref({cover, compile_beams, 1}).
```
Comment (paulo-ferraz-oliveira) [inline src/meck_cover.erl:25]: This is not present in Erlang/OTP 19.3, it seems.

File: src/meck_expect.erl [hunk 2]
```diff
@@ -39,7 +39,7 @@
                         meck_ret_spec:ret_spec()}.
 
 -type func_ari() :: {Func::atom(), Ari::byte()}.
--opaque expect() :: {func_ari(), [func_clause()]}.
+-type expect() :: {func_ari(), [func_clause()]}.
```
Comment (paulo-ferraz-oliveira) [inline src/meck_expect.erl:42]: This is used internally (in a different module), so `dialyzer` complains about broken "opaqueness" if it's not exposed as `type`, but `opaque`.

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

File: src/meck_cover.erl (hunk 1 above)
Comment (eproxus) [reply src/meck_cover.erl:25]: Hmm, we test with 19.3 (more specifically 19.3.6.13 which is  the latest official Docker imager). That would mean that this is tested... The functions are not documented, but should be exported still. Is that what you checked?

**Comment by eproxus** [comment]
@paulo-ferraz-oliveira I for sure would like to get rid of Hamcrest as a dependency. The problem can be solved in a few different ways:
1. Just remove Hamcrest and still "be compatible" without any tests to confirm
2. Remove compatibility (maybe not explicitly in code, but at least not caring about it in the long run)
3. Somehow make it optional (which is how it is now, but not really satisfactory obviously)

**Comment by paulo-ferraz-oliveira** [comment]
> Just remove Hamcrest and still "be compatible" without any tests to confirm

This is part of the issue, for me. `hamcrest` is not actually a dependency. It's just an expectation in certain parts of the code, namely in `meck.erl` and `meck_matcher.erl`. I guess the solution to this (from the top of my head) could be to isolate the function calls in a new function and `dialyzer`-ignore it. Types (or any other kind of static element) would simply be "imported" from `hamcrest`.

> Remove compatibility (maybe not explicitly in code, but at least not caring about it in the long run)

I don't understand what you mean by this.

> Somehow make it optional (which is how it is now, but not really satisfactory obviously)

Touches what I've said before about function isolation and type importing.

Let me see if I can cook something up.
